// Generated by gencpp from file cyber_msgs/LocalizationEstimate.msg
// DO NOT EDIT!


#ifndef CYBER_MSGS_MESSAGE_LOCALIZATIONESTIMATE_H
#define CYBER_MSGS_MESSAGE_LOCALIZATIONESTIMATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>

namespace cyber_msgs
{
template <class ContainerAllocator>
struct LocalizationEstimate_
{
  typedef LocalizationEstimate_<ContainerAllocator> Type;

  LocalizationEstimate_()
    : header()
    , status(0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , pose()
    , velocity()
    , acceleration()  {
    }
  LocalizationEstimate_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(0)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , pose(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _status_type;
  _status_type status;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;





  typedef boost::shared_ptr< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizationEstimate_

typedef ::cyber_msgs::LocalizationEstimate_<std::allocator<void> > LocalizationEstimate;

typedef boost::shared_ptr< ::cyber_msgs::LocalizationEstimate > LocalizationEstimatePtr;
typedef boost::shared_ptr< ::cyber_msgs::LocalizationEstimate const> LocalizationEstimateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator1> & lhs, const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.pose == rhs.pose &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator1> & lhs, const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cyber_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d02fedc16fd5772aae746c920815f84";
  }

  static const char* value(const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d02fedc16fd5772ULL;
  static const uint64_t static_value2 = 0xaae746c920815f84ULL;
};

template<class ContainerAllocator>
struct DataType< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cyber_msgs/LocalizationEstimate";
  }

  static const char* value(const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int8 status\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"geometry_msgs/Pose pose             # Position and orientation in utm \n"
"geometry_msgs/Twist velocity        # Linear and angular velocity\n"
"geometry_msgs/Twist acceleration    # Linear and angular acceleration\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.pose);
      stream.next(m.velocity);
      stream.next(m.acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizationEstimate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cyber_msgs::LocalizationEstimate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cyber_msgs::LocalizationEstimate_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CYBER_MSGS_MESSAGE_LOCALIZATIONESTIMATE_H
